### PR TITLE
Regex Routing, Middleware Callbacks, Parameters Exposed, Chainable

### PR DESCRIPTION
**Pull request by mattneary**
Hey, I was working on something similar and thought I'd bring some cool new ideas to this project.

I gave it a new routing syntax, `app.get('/', function(req, res){}).post(...)`, middleware callbacks to allow for database queries prior to request handling, for example, and exposed the GET/POST parameters as `this.vars` within handlers.

In general, I wanted to give this a solid, expandable foundation should you or I want to build it out into a full framework.

### CODE REVIEW

**Comment by Poincare** [comment]
Hi Matt!

Thanks for the pull request - really makes the project worthwhile! I just did this as a quick one-off, but this commit makes it something I can build on :) 

Merged.

**Comment by mattneary** [comment]
@Poincare  I hate tying myself down to a bloated web framework and I'm sure you're the same way, but wow we have Birbal! Will this be posted to npm? I'm not familiar with the process.

**Comment by Poincare** [comment]
I had it on npm but then they changed the JSON formatting somewhat and the package broke. I'll probably update it.

I used to like Express, but the rift between express 2 and express 3 just ruined it.

**Comment by mattneary** [comment]
Yeah, I've had plenty of issues with different versions of Node, one on my laptop another on the server, etc. 

What are your thoughts on the POST variable parsing? Do you think we should allow for JSON posts etc., or maybe there's a header we can look at to determine which the client has sent?

**Comment by Poincare** [comment]
You could just look at the mime-type, but, obviously, that's not really reliable. You could just assume its a string and then have the user parse it themselves...

We should probably add some form of session management because that's annoying to set up every time.

**Comment by mattneary** [comment]
Alright, we can figure this stuff out as we go.

**Pull request merged**
